version: "3.2"

services:
    FOXY_IGN:        
        image: robosharing/foxy_ign:latest
        devices: 
            - /dev/dri/card0:/dev/dri/card0
            - /dev/dri:/dev/dri
        privileged: true
        # build:
        #     context: .
        #     dockerfile: Dockerfile_foxy_ign     
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - ./libs/robot_for_gazebo:/models/robot_for_gazebo                         
        environment: 
            - DISPLAY=$DISPLAY
            - GAZEBO_MODEL_PATH=/models/robot_for_gazebo
            - GAZEBO_RESOURCE_PATH=/models/robot_for_gazebo
            - IGN_GAZEBO_RESOURCE_PATH=/models/robot_for_gazebo   
        working_dir: /
        command: "sleep 99999999999"
        network_mode: host