version: "3.2"

services:
    ROS2_FOXY:
        image: ros2foxy       
        build:
            context: .
            dockerfile: Dockerfile      
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix                
        environment: 
            - DISPLAY=$DISPLAY          
        working_dir: /code
        command: "sleep 99999999999"
        network_mode: host

    gzweb8:        
        image: osrf/gazebo:gzweb8
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix           
            - ./src:/src           
        environment: 
            - DISPLAY=$DISPLAY          
        #working_dir: /    #     
        command: "sleep 99999999999"
        network_mode: host